### ISSUE TITLE
Looks like this now

### ISSUE THREAD

**Issue by dazz** [dazz/repo-pr-stats#8]
![screenshot - 19 08 2014 - 23 30 33](https://cloud.githubusercontent.com/assets/182954/3973471/3d1b5048-27e8-11e4-8aba-d83044737073.png)

**Comment by willdurand** [comment]
great! [add this screenshot to your readme](http://williamdurand.fr/2013/07/04/on-open-sourcing-libraries/) ;-)

**Comment by dazz** [comment]
Will do, this way I got the screenshot hosted by github :)

**Comment by willdurand** [comment]
tip top

**Comment by dazz** [comment]
@willdurand nice article

**Comment by willdurand** [comment]
thanks!
